### ISSUE TITLE
Suggestion: Accounts & Storable Builds

### ISSUE THREAD

**Issue by Darthmaul** [surmiran/karl#37]
Hey folks,

First off, great repo! I love the project. I was looking to build this exact thing now that I'm into DRG, and I'm pumped to see what you have already.

I was wondering what the appetite is for adding an account system to the functionality here. This would then be leveraged into other features.

The current functionality is the "frontend", and the account system would leverage a new "backend". Users would have accounts, and builds could be stored and shareable on the system. Additionally, you can open up listing of builds, ratings, popular builds, etc.

In essence, allowing this base system to be leveraged to build out a full-scale platform for handling these builds.

I definitely have a desire to help/work on building out this functionality. I am wondering what the contributors here think as a starting point.

If this is not something you have a desire to work on and would rather leave it up to the community to work on these features, fair enough.

**Comment by surmiran** [comment]
Hey, thanks for the kind words. 
Coincidentally, we have just started collaborating with some other devs that started working on similar tools [a few weeks ago](https://www.reddit.com/r/DeepRockGalactic/comments/geqmom/drg_builds_prototype_web_app_to_create_and_share/). So there will be a new version of KARL in the near future. It's gonna feature a fully fledged backend with accounts, voting and discoverability for builds (courtesy of @chaseconey). As well as deep insights into build stats and dps calculation (courtesy of @phg49389).

We started collaborating because we don't think maintaining multiple 'rivalling' apps will do the community any good.
So if you are interested in joining us or helping out, now would definitely be a great time. You can find me on the DRG discord: surmiran#9989.

Cheers

**Comment by Darthmaul** [comment]
Awesome! That's great to hear, looks like you guys are well on-track.

I will connect and maybe there's something I can offer(I have a decent amount of Laravel experience, so I could bring something to the table there).
